name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify course

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Checkout the LibreLingo
      uses: actions/checkout@v2
      with:
        repository: 'kantord/LibreLingo'
        path: LibreLingo


    - name: Install dependencies
      run: |
          python -V
          pip install requests
          pip install Jinja2
          pip install librelingo-json-export
          pip install librelingo-yaml-loader

    - name: Check course
      run: |
          python LibreLingo/apps/tools/librelingo_tools/lili.py --ids --course course/ --images LibreLingo/apps/web/static/images/ --export
